services:
  libgourou:
    container_name: libgourou
    build: ./image
    command:
      - ./dedrm_all.sh
    # entrypoint:
    #   - sleep
    #   - infinity
    profiles:
      - cli
    volumes:
      - ./input:/home/libgourou/input:z
      - ./output:/home/libgourou/output:z
      - ./output_kepub:/home/libgourou/output_kepub:z
      - ./creds:/home/libgourou/.adept:z

  bot:
    container_name: book_bot
    build: ./image
    restart: unless-stopped
    entrypoint:
      - python3
      - bot.py
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 740M
    profiles:
      - bot
    env_file:
      - .env
    volumes:
      - ./input:/home/libgourou/input:z
      - ./output:/home/libgourou/output:z
      - ./output_kepub:/home/libgourou/output_kepub:z
      - ./usercreds:/home/libgourou/credentials:z
