#!/usr/bin/env python3
"""Initialize or rotate the AUTH_KEY_BASE64 in the repository .env file.

Usage:
  python scripts/init_env.py        # create .env with key if missing and print key
  python scripts/init_env.py --force  # overwrite existing key with a new one
"""
import argparse
import base64
import secrets
from pathlib import Path
from dotenv import load_dotenv

_repo_root = Path(__file__).resolve().parents[1]
_env_path = _repo_root / ".env"
load_dotenv(dotenv_path=_env_path)


def generate_key() -> str:
    key = secrets.token_bytes(32)
    return base64.urlsafe_b64encode(key).decode()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Init or rotate AUTH_KEY_BASE64 in .env")
    parser.add_argument("-f", "--force", action="store_true", help="Overwrite existing key")
    args = parser.parse_args()

    if _env_path.exists() and not args.force:
        # try to read current value
        from os import environ
        if environ.get("AUTH_KEY_BASE64"):
            print("AUTH_KEY_BASE64 already set in environment (loaded from .env). Use --force to rotate.")
            print(environ.get("AUTH_KEY_BASE64"))
            raise SystemExit(0)

    key_b64 = generate_key()
    _env_path.parent.mkdir(parents=True, exist_ok=True)
    with _env_path.open("a", encoding="utf-8") as f:
        f.write("\n# Generated by scripts/init_env.py\n")
        f.write(f"AUTH_KEY_BASE64={key_b64}\n")

    print("Wrote AUTH_KEY_BASE64 to .env")
    print(key_b64)
